### ISSUE TITLE
Design pt 2.

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/nft-marketplace#1]
1) Default view https://zpl.io/a3J1pZl
![image](https://user-images.githubusercontent.com/47353570/140495270-9cc89846-72c3-4a82-b25f-0ddc123382f6.png)

2) Reduce the empty space at the top of the screen. 
Move Title, User account and Key button higher. 
![image](https://user-images.githubusercontent.com/47353570/140495459-255122fa-db5b-481a-937a-d110d985d565.png)

3) Make Key button as icon.
![image](https://user-images.githubusercontent.com/47353570/140495517-6e7cfce1-3fd0-4c31-9bb9-fc6010e63ca4.png)

4) Make 2 blocks: Balance and Stats that hidden dy default.
![image](https://user-images.githubusercontent.com/47353570/140495563-58c20567-35f2-485c-92c4-263fd9c05ef2.png)

5) Open state for Balance and Stats https://zpl.io/awlJ7qn
Make 18K instead of 18000 if there is no free space.
![image](https://user-images.githubusercontent.com/47353570/140495655-652a6bed-e381-48ef-93ac-fe8921c6e0c3.png)

6) Remove tab "Mine" cuz we have new filter "Author".
![image](https://user-images.githubusercontent.com/47353570/140495707-4c5c1487-d0e6-452e-8c79-c4168188a0f8.png)

7) New filter "Author" here https://github.com/BeamMW/beam-dapps/issues/54

**Comment by chapati** [comment]
Desgin has been changed from what is described above. Not relevant anymore

**Comment by Denis-Asipenko** [comment]
the design does not correspond to the implemented one.irrelevant
