### ISSUE TITLE
Gallery Migration 

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#100]
Mainnet gallery has been migrated to dappent.
Please check that migration is correct.

**Comment by AndreyDyakonov** [comment]
Gallery migration was incorrect
The artist's total number of NFTs remained the same as it was, but some of my NFTs began to belong to another user, and NFTs of other users belong to me 

Artist key: 094c4e14f3df7639f9ac94123a106b3dc7d0499edcfac875da49f40e2a84f54701

Owned NFTs
![2022-06-29_18-01-31](https://user-images.githubusercontent.com/85252690/176473117-98677b8e-86a7-4156-b10f-f5e6c95bc7f1.png)

On sale
![photo_2022-06-29_18-00-21](https://user-images.githubusercontent.com/85252690/176473194-835f6875-8226-430b-833c-f4322fababe7.jpg)

Sold
![photo_2022-06-29_18-00-34](https://user-images.githubusercontent.com/85252690/176473271-2f588eb5-59a3-49c9-9e7d-774f7f2d6f8d.jpg)
