### ISSUE TITLE
Can't put "like" NFT

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/nft-marketplace#102]
After migration gallery, "likes" didn't transfered and the opportunity to evaluate the NFT with a "like" disappeared

https://user-images.githubusercontent.com/85252690/176475347-1dab4139-86ca-4318-b79f-d3bd66fc48b0.mp4

**Comment by chapati** [comment]
Likes will not be migrated.

**Comment by AndreyDyakonov** [comment]
Checked
