### ISSUE TITLE
Transfer NFT: incorrect work

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/nft-marketplace#103]
Transferred NFT remains as owned in the sender's wallet and isn't displayed as owned in the receiver's wallet There are errors when sender or receiver try to use this NFT

Sender's wallet
![01](https://user-images.githubusercontent.com/68267190/176616240-b9031d67-9ddf-417f-a007-b181e0308dd5.gif)

Receiver's wallet
![03](https://user-images.githubusercontent.com/68267190/176616306-0c5a0b80-ebf6-4bfb-b1f5-63ca64c5d9f3.gif)

**Comment by Denis-Asipenko** [comment]
checked
