### ISSUE TITLE
Crash on large images

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/nft-marketplace#11]
When the user selects big size image to upload the Wallet crashes

Steps:
- open wallet with Gallery admin rights
- go to the gallery 
- chose an artist and select big size image to upload
Actual result: Wallet crashes
Expected: Wallet isn't crashed, a warning appeared

**Comment by chapati** [comment]
500KB limit is introduced

**Comment by AndreyDyakonov** [comment]
Checked
