### ISSUE TITLE
[BETA] Need to add the ability to cancel NFT offer

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/nft-marketplace#15]
As a seller, I want to have the ability to cancel my NFT offer because:
-  I could make a mistake in the price
- I changed my mind about selling
![image](https://user-images.githubusercontent.com/44496108/139428730-ce5a8040-cbff-49e6-b4a6-732f6035b72e.png)

**Comment by chapati** [comment]
Would be implemented as a part of #4
