### ISSUE TITLE
Placeholder "NFT Gallery is coming soon…"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/nft-marketplace#16]
Please leave button "Show my public key" and add image with text "NFT Gallery is coming soon…
https://zpl.io/bo7kjzG
![image](https://user-images.githubusercontent.com/47353570/139059558-c0f6f56a-bf83-4299-a98e-25ca274ea60a.png)

**Comment by chapati** [comment]
This done and not relevant anymore.
