### ISSUE TITLE
Change artwork price

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/nft-marketplace#4]
1) Add actions (3 dots) near the price on artworks in tab On sale. https://zpl.io/VQ3Mlw9
![image](https://user-images.githubusercontent.com/47353570/139873896-97137360-71d8-451c-9e09-af16dbd2fcbd.png)

2) Add there "update the price"

3) Popup confirmation before price updating https://zpl.io/25lGqqe
![image](https://user-images.githubusercontent.com/47353570/139874079-e88f541f-142f-41b2-b7bc-f4b2bbdb0059.png)

4) Update the price popup https://zpl.io/2yRzmlL
![image](https://user-images.githubusercontent.com/47353570/139873847-3f69e83b-077a-4dfb-9c24-9f64e68adede.png)

**Comment by chapati** [comment]
1. Sell and change price dialogs should not allow 0 price
2. New delete (rename to 'remove from sale') item in popup menu should perform the same actions as 0 price dialog now

**Comment by AndreyDyakonov** [comment]
Checked
