### ISSUE TITLE
Paginator changes

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#45]
Paginator looks strange. it has square angles when NFT frames and buttons have round angles. please, make paginator angles close to nft frame (visual)

https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=567%3A1084
<img width="686" alt="Снимок экрана 2022-04-01 в 14 19 38" src="https://user-images.githubusercontent.com/94360080/161253574-6ecbf3ed-9733-40a6-b0e1-4728a758e0c5.png">

**Comment by dariatarakanova** [comment]
Done
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=567%3A1084
<img width="685" alt="image" src="https://user-images.githubusercontent.com/47353570/161981838-9d9df94b-bac3-4308-af59-67a4343c52c4.png">
