### ISSUE TITLE
Admin panel - NFT gallery | Changes

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#46]
1. Profile images -> User's profiles
2. Collection banners -> Collection profiles
3. Select all - to the left part of screen. 
4. Nft check box place on the nft.
5. no price and menu on nft card, let's save the place.
6. paginator is always located above the buttons 
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=567%3A1084
<img width="581" alt="Снимок экрана 2022-04-01 в 14 31 16" src="https://user-images.githubusercontent.com/94360080/161255715-f5ae20aa-60e8-4346-9e62-1faea0b7a7ce.png">

**Comment by VikMaevskaya** [comment]
paginator located between NFT and buttons
<img width="321" alt="Снимок экрана 2022-04-06 в 16 37 56" src="https://user-images.githubusercontent.com/94360080/161987620-622f5b76-cacc-4bd6-8956-400d0ff01501.png">

**Comment by dariatarakanova** [comment]
done here 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/47353570/162008690-ed662564-c979-42ee-b97f-a8062bbc263a.png">
