### ISSUE TITLE
Admin panel - Users Profiles approve

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#47]
for this release, we won't have automatically approved text or links. 
Need to make a page with 3 users' profile information. 

![admin panel profile approve (2)](https://user-images.githubusercontent.com/94360080/161798414-eb0f761a-5daf-4559-a732-0f4fe39560ee.png)

**Comment by dariatarakanova** [comment]
@VikMaevskaya please check this screen https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=826%3A2087

**Comment by VikMaevskaya** [comment]
for artist's name and About please use max number of characters. about is 150 symb.

**Comment by dariatarakanova** [comment]
here are 30 and 150 symbols for name and about fields
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=826%3A2087
