### ISSUE TITLE
Admin panel - Collection information approve

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#48]
for this release, we won't have automatically approved text or links.
Need to make a page with 5 collection's information

![admin panel collection approve (1)](https://user-images.githubusercontent.com/94360080/161798535-573296a9-08a5-474d-a292-abf612ec4584.png)

**Comment by dariatarakanova** [comment]
@VikMaevskaya https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=826%3A2432

Can admin edit text info?

**Comment by VikMaevskaya** [comment]
> @VikMaevskaya https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=826%3A2432
> 
> Can admin edit text info?

admin couldn't edit any info
