### ISSUE TITLE
Add text for all pages Create, add, change

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#49]
Add text for all pages Create, add, change.
Location: under the current text

Text:
Create Artist
After your artist account is created it would not be visible until reviewed by a moderator. 

Change Artist's info
After your artist information is changed it would not be visible until reviewed by a moderator. 

Create Collection
After your collection is created it would not be visible until reviewed by a moderator. 

Change Collections' info
After your collection information is changed it would not be visible until reviewed by a moderator. 

Create NFT
After your NFT is added it would not be visible until reviewed by a moderator. 

Change NFT
After your NFT information is changed it would not be visible until reviewed by a moderator. 

https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=94%3A497

https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=25%3A1172

https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=26%3A1074
<img width="678" alt="Снимок экрана 2022-04-04 в 10 28 57" src="https://user-images.githubusercontent.com/94360080/161494716-cc52324a-f8c1-4b81-8a09-9a83071d81a6.png">

**Comment by dariatarakanova** [comment]
@VikMaevskaya added as you requested
