### ISSUE TITLE
Become an artist

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#50]
- [x] User should be able to become an artist himself
UI is in https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=57%3A487 -> Become an artist section

**Comment by chapati** [comment]
Need to move avatar upload according to design.

Now:

![gnome-shell-screenshot-arewaf](https://user-images.githubusercontent.com/12074933/162039899-a42515bf-46f9-4368-b801-010d98f2bccb.png)

Expected:

![gnome-shell-screenshot-h1dfiq](https://user-images.githubusercontent.com/12074933/162039987-b264c70e-98ee-4bd4-8c04-89eacd27f31c.png)

**Comment by chapati** [comment]
![gnome-shell-screenshot-10kgzs](https://user-images.githubusercontent.com/12074933/163001313-af9a4ea2-9873-4a9d-b3d2-eed1183306ed.png)
[ ] move error higher
[ ] buttons should not jump when error is displayed

**Comment by chapati** [comment]
- [ ] Still not like on design, should be moved upper

![Screenshot-20220426220851-426x174](https://user-images.githubusercontent.com/12074933/165374464-fecd855c-b9c2-43b3-b5b2-25250d45d1db.png)

**Comment by Denis-Asipenko** [comment]
checked
