### ISSUE TITLE
Need to create generic images for artist, artist banner, collection banner, nft

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#51]
Need to create generic images for artist, artist banner, collection banner, nft
the one img for every position (4 imgs). They will be shown automatically if the user forgot to upload a personal one.

specification:
all img less than 150 kb

size in px:
1. artist logo 350x350
2. Collection and User banner 1400x400
3. NFT 600x600

**Comment by dariatarakanova** [comment]
Hello @VikMaevskaya 
please have a look here (and next screens) https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=994%3A1220

**Comment by VikMaevskaya** [comment]
The colors are great! I think about gradient squares. The beam has a triangle. Let's try to use them, please. or combine fo the triangles like here
<img width="432" alt="Снимок экрана 2022-04-12 в 12 51 14" src="https://user-images.githubusercontent.com/94360080/162944204-ab545890-8585-461b-944d-595974daf7ac.png">

for NFT and Artist logo I think we need more identity. 
for example, a nongender shape. and some kind of shape for nft.
![users-3-icon](https://user-images.githubusercontent.com/94360080/162946596-562aec79-e806-417e-aa9b-1502c0eeebc5.png)
