### ISSUE TITLE
Design for the Error pop-up

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#52]
Need to create the error pop-up. Example from the Dapp store.

text:
NFT gallery
Something went wrong. The page will be automatically restarted. 
If you came across this problem again, copy the following text {coppy text button} and send it to support, please.

Restarting in 7 sec.  ( count down to 1)
ok button

![uninstall-fail (2)](https://user-images.githubusercontent.com/94360080/162965846-c3d182de-ec0b-4ae5-bb1b-f671dada762a.png)

example of error text
![photo_2022-04-12_15-48-26](https://user-images.githubusercontent.com/94360080/162965930-85db1ecc-a081-4303-9e63-94656fca7d66.jpg)

**Comment by dariatarakanova** [comment]
@VikMaevskaya  https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2?node-id=1058%3A1425
