### ISSUE TITLE
Contract - Roles

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#53]
- [x] There should be the following roles in contract: user, manager, artist
- [x] user ->  view_collections(_stats) & view_artworks(_stats) & view_artists(_stats) - what normal user can view, approved only
- [x] manager -> view_collections(_stats) & view_artworks(_stats) & view_artists(_stats) - all object in the system
- [x] artist -> view_collections(_stats) & view_artworks(_stats) + view (self) - everything that belongs to artists, approved and not approved

----

- [x] user -> view_collections - all approved collections
- [x] user -> view_artworks - all approved artworks
- [x] user -> view_owned_artworks + view_owned_artworks_stats - all owned artworks (regardless of approved)
- [x] artist -> view_collections - all created collections (regardless of approved)
- [x] artist -> view_artworks - all created artworks (regardless of approved)
- [x] artist -> view_sales + view_sales_stats - all sale events for artworks (regardless of approved) - investigate
- [x] moderator -> view_collections - all pending collections
- [x] moderator -> view_artworks - all pending artworks
- [x] view_collections -> remove artworks array, return count of object according to the role
- [x] add view_collection (id) for each role, remove view_artworks:by collection filter
- [x] idx0 + count should work fast on read (including role filters) for user -> colls, artworks; artist -> colls, arworks, moderator -> colls, artworks, artists
- [x] ids should work fast for manager -> artists 
- [x] h0 + count should work fast for all methods for manager

**Comment by Denis-Asipenko** [comment]
checked
