### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#58]
- [x] make tooltip on become artist look according design. now default tooltip is displayed. Merge master to your branch before doing the task. Do not implement arrow. Just simple plain square at the moment.

![Screenshot-20220421000639-370x199](https://user-images.githubusercontent.com/12074933/164323022-577ea879-67f6-4b3c-aa5a-19dacad97d74.png)

- [x] tooltip should not be cut by the client border. If tooltip extends beyond the screen move it to the left.

**Comment by KatsiarynaV** [comment]
Please, place tooltip above the buttons as in the design

![02](https://user-images.githubusercontent.com/68267190/174830839-d5f0ab71-719e-4474-9d40-67c6bac1c4ab.jpg)
![01](https://user-images.githubusercontent.com/68267190/174830851-c5e731ce-1f80-47cd-8ffc-9b569690c7e2.jpg)

**Comment by KatsiarynaV** [comment]
Checked
