### ISSUE TITLE
APP in browser

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#6]
Need to test how app behaves in browser

1) In normal browsers: chrome (should work), firefox, edge - should show install supported (chromium-based) browser. If wallet is not connected (headless mode) should not allow actions with money and suggest connecting/installing extensions
2) In mobile browser - should show install wallet

**Comment by chapati** [comment]
Please use this URL to test https://apps-dappnet.beam.mw/app-same-origin/gallery20/
Also need to install web wallet (ensure that build is from dappnet) and test how web version works with the web wallet.

**Comment by chapati** [comment]
All actions that are connected with uploading images would fail in browser. Should use desktop wallet or the action will fail. So this is normal that it fails but it is better to display warning and disable these actions. I've added the following message:

![Screenshot-20220624214855-563x299](https://user-images.githubusercontent.com/12074933/175646897-f4eb1f54-11d8-4937-9946-f99eab2ac806.png)

Check that it is displayed when user tries to edit artist/nft/collection

**Comment by AndreyDyakonov** [comment]
Problem with android remains:
when we open gallery in mobile browser in Android - appears error message

error message:
TypeError: Cannot read properties of undefined (reading 'callWalletApi')
at Utils.callApi (https://apps-dappnet.beam.mw/app-same-origin/gallery20/main.bundle.js:40145:23)
at https://apps-dappnet.beam.mw/app-same-origin/gallery20/main.bundle.js:40119:13
at new Promise ()
at Utils.callApiAsync (https://apps-dappnet.beam.mw/app-same-origin/gallery20/main.bundle.js:40118:12)
at Object.checkCID (https://apps-dappnet.beam.mw/app-same-origin/gallery20/main.bundle.js:38429:63)
at async https://apps-dappnet.beam.mw/app-same-origin/gallery20/main.bundle.js:38345:7

<img width="450" src="https://user-images.githubusercontent.com/85252690/175931454-ddbdd2de-6ec6-40c1-bfd6-20d3fe2fc911.jpg">

**Comment by chapati** [comment]
Please try now

**Comment by AndreyDyakonov** [comment]
Checked
