### ISSUE TITLE
NFT Page - desgin update

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#62]
Update NFT page according to design

- [x] Add creator & Collection lines
- [x] Ensure that right part of the screen with info is always the same size as the left part with preview
- [x] if NFT has long description dots at the end should be displayed

![Screenshot-20220426163025-679x690](https://user-images.githubusercontent.com/12074933/165311985-d4b436b7-5e15-4ffe-82d6-4fc22c4f7e5f.png)

**Comment by KatsiarynaV** [comment]
Checked
