### ISSUE TITLE
Moderator - artist approve UI

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#63]
- [x] add 'artist_approve.vue' component that implements artist preview for moderator

![Screenshot-20220426163705-619x171](https://user-images.githubusercontent.com/12074933/165312698-c4fe607f-f43a-4c4f-84e1-c31e7d892655.png)

- [x] About me should be the last item. Component should display full about me text.

**Comment by KatsiarynaV** [comment]
Checked
