### ISSUE TITLE
Contract: likes

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#68]
At the moment user:vote creates the following transaction

![Screenshot-20220508104020-938x686](https://user-images.githubusercontent.com/12074933/167286654-7080637d-2779-4f46-afde-593e3803173f.png)

- [x] deploy/fix contract to use custom asset for votes
- [x] set vote reward to 1 ASSET
- [x] add asset rewards to the contract - role=manager,action=add_rewards

We need to be able to vote. On each contract deploy ensure that the actions above are performed. 
Also implement the following:

- [ ] when artwork changes state from 'approved' to anything else clear all likes related info: set likes count to 0 (impressions), clear my_impression flag

**Comment by iKapitonau** [comment]
It's too complicated to delete all impressions of an artwork for now.
