### ISSUE TITLE
Changes Admin panel NFT approve.

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#69]
NFT gallery Admin panel should looks like Artist profile approve.
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=826%3A2087
Admin should approve:
Name 35 symb max
Description 300 symb max
NFT

**Comment by dariatarakanova** [comment]
Here is an updated design 
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1415%3A1230
