### ISSUE TITLE
Design pt 1.

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/nft-marketplace#7]
1) Icons and DApps states in DApp store https://zpl.io/VYzPlvm
![image](https://user-images.githubusercontent.com/47353570/138743437-4f549fa2-1f5b-4d5b-b900-8aa058778479.png)

2) Empty marketplace placeholder https://zpl.io/adoR6m7 (if user is a seller)
![image](https://user-images.githubusercontent.com/47353570/138917949-4a8ce896-7787-4232-8286-5b6af8b6f321.png)

2.1) Empty marketplace placeholder https://zpl.io/V1LMRYk (if user is not a seller)
![image](https://user-images.githubusercontent.com/47353570/138918048-4cd7aa1a-417b-4369-aaf5-a11b6c1279ca.png)

3) Show public key https://zpl.io/adoR6WK
![image](https://user-images.githubusercontent.com/47353570/138900302-7857a54d-4477-446f-8b64-877fa71871d9.png)

4) Main screen (if user is a seller) https://zpl.io/V0OP84x
![image](https://user-images.githubusercontent.com/47353570/138918250-03adc644-b6eb-4648-af1e-1321df6bd821.png)

4.1) Main screen (if user is not a seller) https://zpl.io/2ZAqlE4
![image](https://user-images.githubusercontent.com/47353570/138918290-4d796612-8536-4d7c-8e3b-d4ed02ffb3ae.png)

4.2) Important: no need to show tabs (Mine, On sale, Sold, Liked) if they are empty.

5) Do not display button "Buy" if NFT was sold. Place there "sold" text. https://zpl.io/V0OP84x
![image](https://user-images.githubusercontent.com/47353570/138901121-3dd763ee-fc7b-40af-b662-f52241cdd24b.png)

6) Add tag "mine" to user's own artworks https://zpl.io/V0OP84x
![image](https://user-images.githubusercontent.com/47353570/138901294-797fd4fe-787b-49f4-931e-1891f83895ad.png)

Tabs:

7) Tab "Mine" include all user's NFTs https://zpl.io/VkPKgjK
![image](https://user-images.githubusercontent.com/47353570/138918712-65cecce6-0f6b-404a-9629-2f43ffbdf67a.png)

8) Tab "On sale" include only NFTs that were put up for sale (user set the price) https://zpl.io/VQ3Mlw9
![image](https://user-images.githubusercontent.com/47353570/138918760-60cd70c8-2b1c-4dc7-8e6f-23bed49ab465.png)

9) Tab "sold" includes only sold artworks https://zpl.io/bJ6ODBW
![image](https://user-images.githubusercontent.com/47353570/138905478-b0f6723c-5d3d-4956-af9c-1dbaee4d0b73.png)

10) Tab "Liked" include liked NFTs https://zpl.io/2pqx35N
![image](https://user-images.githubusercontent.com/47353570/138907378-e7da904e-8657-4fed-8288-8193a1579e65.png)

11) Filter and sorting" open view https://zpl.io/VQ3Mlw9
![image](https://user-images.githubusercontent.com/47353570/138905829-7913c203-40c3-418e-a934-642ed0bdcdea.png)

Actions:

12) "Withdraw" is opening withdraw dialog where uses is setting amount to withdraw https://zpl.io/a3J0MnN
![image](https://user-images.githubusercontent.com/47353570/138918878-5879ba38-9716-46e4-a64a-4421a280cdf8.png)

13) After "Withdraw" amount dialog  - display withdraw confirmation dialog. https://zpl.io/aB3jQee
![image](https://user-images.githubusercontent.com/47353570/138918973-26ecfffa-de40-423b-a6f9-5f8e855ddfb8.png)

14) Click on "Buy" is opening confirm dialog https://zpl.io/b6WJXrN
![image](https://user-images.githubusercontent.com/47353570/138919053-e504ed29-e4b8-4179-89df-1373e10b3b9c.png)

15) Click on "Sell" allows user to set the price. https://zpl.io/V1LM70J
![image](https://user-images.githubusercontent.com/47353570/138919162-56166823-d1e7-46e1-9fa0-ee9068feb59c.png)

16) After setting the price - display confirmation dialog https://zpl.io/agE934O
![image](https://user-images.githubusercontent.com/47353570/138919229-84602147-82c3-407e-a1b3-e1d96291ff07.png)

17) Click on "like"  icon heart is becoming red and confirmation dialog is opening https://zpl.io/awlyEKn
![image](https://user-images.githubusercontent.com/47353570/138919280-27bc1632-4ce3-498e-9ebb-b3362ae00f98.png)

18) Click on "unlike"  icon heart is becoming transparent with white border and confirmation dialog is opening also https://zpl.io/aRkmlON
![image](https://user-images.githubusercontent.com/47353570/138919354-771c30c3-d188-42bf-9133-86d68103a454.png)

**Comment by KatsiarynaV** [comment]
This design is not relevant to implemented one
