### ISSUE TITLE
to add 'transfer' icon to NFT page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/nft-marketplace#71]
min size nft info block w 480px h 320px
In the bracket, the numb of max characters, please don't change any text.
Near the share Icon, we need to add the transfer Icon.

https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=894%3A1109
<img width="773" alt="Снимок экрана 2022-05-20 в 10 51 16" src="https://user-images.githubusercontent.com/94360080/169480541-c5f993d7-a7a8-4fcd-9016-3812b1d961a7.png">

**Comment by dariatarakanova** [comment]
1) Added TRANSFER icon  https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1486%3A1253
<img width="599" alt="image" src="https://user-images.githubusercontent.com/47353570/169543964-85dd17d2-3ad0-46e1-9c5d-3bf30f0a532d.png">

2) After click icon opens popup https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1489%3A1410
<img width="589" alt="image" src="https://user-images.githubusercontent.com/47353570/169544080-88d960fe-f5e2-4847-9405-e9ae996ab7c9.png">

3) Popup with pasted address https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1489%3A1761
<img width="499" alt="image" src="https://user-images.githubusercontent.com/47353570/169544153-12c5b751-066f-4e50-bd7b-6d393b66ae80.png">

4) Notification https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1489%3A2110
<img width="602" alt="image" src="https://user-images.githubusercontent.com/47353570/169544298-b5fc1733-5616-472c-94d4-881c41568d46.png">
