### ISSUE TITLE
Sales + transfer

### ISSUE THREAD

**Issue by chapati** [BeamMW/nft-marketplace#79]
- [x] Transfer NFT action should update sales list with price 0
- [x] Transfer NFT action should update first_sale with price 0

**Comment by Denis-Asipenko** [comment]
When transferring the NFT, the set price by the previous owner remains unchanged and will not change by 0

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/45556620/175294435-27dc5915-9bd6-4de9-9219-e35c75149f10.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/45556620/175294286-88559f08-2a72-40c7-80a5-cb8c00fe3939.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/45556620/175294336-9b854316-885b-4985-89cc-638bf17e9bcf.png">

**Comment by Denis-Asipenko** [comment]
This fix did not work
> Fixed in the [commit](https://github.com/BeamMW/nft-marketplace/commit/2451ea2c94857aae3ec760dcd4d2fee50d552484).

**Comment by Denis-Asipenko** [comment]
waiting for a fix https://github.com/BeamMW/nft-marketplace/issues/103
