### ISSUE TITLE
Bulk approve

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/nft-marketplace#86]
Moderator should be able to approve multiple collections at once
Now when moderator selects multiple collections, the transaction fails

![01](https://user-images.githubusercontent.com/68267190/174084235-a142c9d7-a123-4797-860c-085e395ba97c.gif)
![08](https://user-images.githubusercontent.com/68267190/174083519-2b2108cb-9812-4cba-a585-7a14af0225a1.jpg)

**Comment by chapati** [comment]
Should be OK now. Check also NFTs & Artists please.

**Comment by KatsiarynaV** [comment]
Checked
