### ISSUE TITLE
Become an artist UI size

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/nft-marketplace#89]
1. If we use Macbook with 13.3" (2560x1600 and 16:10 aspect ratio) display in window size wallet (1830x1520) then  buttons "cancel" and "create account" doesn't display  
(they display only in full size wallet)

<img width="650" src="https://user-images.githubusercontent.com/85252690/174163264-f17d6dea-2ad1-4626-8a74-3f13a5af81f7.jpg">

2. If we use a display with a width resolution below 900 pixels then  buttons "cancel" and "create account" doesn't display  

<img width="650" src="https://user-images.githubusercontent.com/85252690/174164005-bead847a-3cca-4d92-9b3a-39f2ccbb13f4.jpg">

**Comment by AndreyDyakonov** [comment]
If we use wallet with a display with a width resolution below 900 pixels or Macbook with 13.3" (2560x1600)
the icons of social networks when scrolling go beyond the fields 

https://user-images.githubusercontent.com/85252690/174542372-59831b32-b9a5-47c5-b2bf-2e94275b0144.mp4

**Comment by chapati** [comment]
Our client supports minimal width 1024px. It would be displayed even on screens which are smaller but such resolutions are not supported and we do not usually fix issues with such screens.

**Comment by chapati** [comment]
Try now please

**Comment by AndreyDyakonov** [comment]
Checked
