### ISSUE TITLE
Moderator panel - incorrect display with long site link 

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/nft-marketplace#94]
When user create Artist account or create new collection  and put long site name (link) then for moderator in moderator panel (in window mode wallet) Artist banner or collection image are displayed truncated and shifted to the left

![2022-06-21_18-58-34](https://user-images.githubusercontent.com/85252690/175063584-6b061a40-b60c-4752-8d99-cbc175887234.png)

**Comment by chapati** [comment]
1. This also happens for collections with long link. Please check that it is fixed.
2. Long urls should display ... at the end

This is the correct view:

![Screenshot-20220624212154-956x360](https://user-images.githubusercontent.com/12074933/175634272-8639d7ef-1620-4f4e-8eea-820e7de51525.png)

**Comment by AndreyDyakonov** [comment]
Checked
